// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/nkwa/pay-go/models/components"
)

type GetAvailabilityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Operator availability data
	Availabilities []components.Availability
}

func (o *GetAvailabilityResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAvailabilityResponse) GetAvailabilities() []components.Availability {
	if o == nil {
		return nil
	}
	return o.Availabilities
}
