// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/nkwa/pay-go/models/components"
)

type GetPaymentsIDRequest struct {
	// ID of payment to fetch
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetPaymentsIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetPaymentsIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Payment retrieved successfully
	Payment *components.Payment
}

func (o *GetPaymentsIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetPaymentsIDResponse) GetPayment() *components.Payment {
	if o == nil {
		return nil
	}
	return o.Payment
}
