// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/nkwa/pay-go/models/components"
)

type PostCollectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Collection request created and pending
	Payment *components.Payment
}

func (o *PostCollectResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostCollectResponse) GetPayment() *components.Payment {
	if o == nil {
		return nil
	}
	return o.Payment
}
