// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaymentRequest struct {
	Amount      int64  `json:"amount"`
	PhoneNumber string `json:"phoneNumber"`
}

func (o *PaymentRequest) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *PaymentRequest) GetPhoneNumber() string {
	if o == nil {
		return ""
	}
	return o.PhoneNumber
}
