// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type PaymentType string

const (
	PaymentTypeCollection   PaymentType = "collection"
	PaymentTypeDisbursement PaymentType = "disbursement"
)

func (e PaymentType) ToPointer() *PaymentType {
	return &e
}
func (e *PaymentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "collection":
		fallthrough
	case "disbursement":
		*e = PaymentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentType: %v", v)
	}
}
