// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/nkwa/pay-go/internal/utils"
	"time"
)

type Payment struct {
	Amount          *int64           `json:"amount,omitempty"`
	CreatedAt       *time.Time       `json:"createdAt,omitempty"`
	Currency        *string          `json:"currency,omitempty"`
	Description     *string          `json:"description,omitempty"`
	Fee             *int64           `json:"fee,omitempty"`
	ID              *string          `json:"id,omitempty"`
	MerchantID      *int64           `json:"merchantId,omitempty"`
	PaymentType     *PaymentType     `json:"paymentType,omitempty"`
	PhoneNumber     *string          `json:"phoneNumber,omitempty"`
	Status          *PaymentStatus   `json:"status,omitempty"`
	TelecomOperator *TelecomOperator `json:"telecomOperator,omitempty"`
	UpdatedAt       *time.Time       `json:"updatedAt,omitempty"`
}

func (p Payment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Payment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Payment) GetAmount() *int64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *Payment) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Payment) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *Payment) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Payment) GetFee() *int64 {
	if o == nil {
		return nil
	}
	return o.Fee
}

func (o *Payment) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Payment) GetMerchantID() *int64 {
	if o == nil {
		return nil
	}
	return o.MerchantID
}

func (o *Payment) GetPaymentType() *PaymentType {
	if o == nil {
		return nil
	}
	return o.PaymentType
}

func (o *Payment) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}

func (o *Payment) GetStatus() *PaymentStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *Payment) GetTelecomOperator() *TelecomOperator {
	if o == nil {
		return nil
	}
	return o.TelecomOperator
}

func (o *Payment) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
