// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	APIKeyAuth *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key,env=pay_api_key_auth"`
}

func (o *Security) GetAPIKeyAuth() *string {
	if o == nil {
		return nil
	}
	return o.APIKeyAuth
}
