// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TelecomOperator string

const (
	TelecomOperatorMtn    TelecomOperator = "mtn"
	TelecomOperatorOrange TelecomOperator = "orange"
)

func (e TelecomOperator) ToPointer() *TelecomOperator {
	return &e
}
func (e *TelecomOperator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mtn":
		fallthrough
	case "orange":
		*e = TelecomOperator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TelecomOperator: %v", v)
	}
}
