// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
)

type HTTPError struct {
	Details    []any   `json:"details,omitempty"`
	Message    *string `json:"message,omitempty"`
	StatusCode *int64  `json:"statusCode,omitempty"`
}

var _ error = &HTTPError{}

func (e *HTTPError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
