workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Nkwa Pay API:
        inputs:
            - location: https://raw.githubusercontent.com/nkwa/pay-postman/refs/heads/main/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/nkwa/pay/nkwa-pay-api
targets:
    pay:
        target: go
        source: Nkwa Pay API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/nkwa/pay/nkwa-pay-api-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
